#!/usr/bin/bash

# .csv (generated by JCR as those from Steven Bell) -> .tsv  (can be handled by GitHub)

chmod -x csv/*

ls csv | \
xargs -l basename -s .csv | \
parallel "awk '/Rank|Journal name/,/Copyright/' csv/{}.csv | awk NF | grep -v Copyright | tr ',' '\t'> {}.tsv"
