site_name: CEU journal club
repo_url: https://github.com/cambridge-ceu/CEU-journal-club
edit_uri: ""
nav:
  - "   ": README.md
  - Clubs:
    - HLRI: mike.md
    - SRL+HRLI: schedule.md
  - FullCalendar:
    - "A full-sized drag & drop JavaScript event calendar":
      - "Project website and demos": http://fullcalendar.io/
      - Documentation: http://fullcalendar.io/docs
      - Support: http://fullcalendar.io/support
    - Packages:
      - fullcalendar-4.3.1/packages/bootstrap/README.md
      - fullcalendar-4.3.1/packages/core/README.md
      - fullcalendar-4.3.1/packages/daygrid/README.md
      - fullcalendar-4.3.1/packages/google-calendar/README.md
      - fullcalendar-4.3.1/packages/interaction/README.md
      - fullcalendar-4.3.1/packages/list/README.md
      - fullcalendar-4.3.1/packages/luxon/README.md
      - fullcalendar-4.3.1/packages/moment/README.md
      - fullcalendar-4.3.1/packages/moment-timezone/README.md
      - fullcalendar-4.3.1/packages/rrule/README.md
      - fullcalendar-4.3.1/packages/timegrid/README.md
  - JIF: JIF.md
  - Notes: Notes.md
  - Utilities:
    - AuthorArranger: https://authorarranger.nci.nih.gov/
    - biomrenderR: https://github.com/xizhou/biomenderR
    - EndNote (register/download/key): https://cambridge.store.academia.co.uk/
    - MyEndNoteWeb: https://access.clarivate.com/login?app=endnote
    - PMC-LLaMA: https://github.com/chaoyi-wu/PMC-LLaMA
    - pubMR: https://github.com/xizhou/pubMR
    - PubPeer: https://pubpeer.com/
    - Sciwheel: https://sciwheel.com/
    - Springer Nature's Journal Finder: https://link.springer.com/journals
    - Tools to support and steward research culture: https://royalsociety.org/topics-policy/projects/research-culture/tools-for-support/
theme:
    name: mkdocs
    nav_style: dark
    highlightjs: true
    hljs_languages:
        - Bash
        - HTML
        - Java
        - JavaScript
        - Perl
        - Python
        - R
        - rust
        - yaml
extra_css:
  - stylesheets/extra.css
plugins:
    - search
    - mermaid2
markdown_extensions:
  - attr_list
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
